// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgm3K6AuUFMZLc7EZnQW7pKI7zDGyA43c',
    appId: '1:9819698541:web:97bd81caeab00b22409664',
    messagingSenderId: '9819698541',
    projectId: 'nexo-360-9ed4c',
    authDomain: 'nexo-360-9ed4c.firebaseapp.com',
    storageBucket: 'nexo-360-9ed4c.firebasestorage.app',
    measurementId: 'G-ZZQ3MDFSJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoS1_Ydr95otITGMwUczkf0zoAFXfVD1Y',
    appId: '1:9819698541:android:cfb70d86d2e91453409664',
    messagingSenderId: '9819698541',
    projectId: 'nexo-360-9ed4c',
    storageBucket: 'nexo-360-9ed4c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaIGp1m3oiO99KkqknwhQ9mc_iNUIlho',
    appId: '1:9819698541:ios:e471b3a59e589f04409664',
    messagingSenderId: '9819698541',
    projectId: 'nexo-360-9ed4c',
    storageBucket: 'nexo-360-9ed4c.firebasestorage.app',
    iosBundleId: 'com.example.nexo360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqaIGp1m3oiO99KkqknwhQ9mc_iNUIlho',
    appId: '1:9819698541:ios:e471b3a59e589f04409664',
    messagingSenderId: '9819698541',
    projectId: 'nexo-360-9ed4c',
    storageBucket: 'nexo-360-9ed4c.firebasestorage.app',
    iosBundleId: 'com.example.nexo360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgm3K6AuUFMZLc7EZnQW7pKI7zDGyA43c',
    appId: '1:9819698541:web:1929ed9a207db8da409664',
    messagingSenderId: '9819698541',
    projectId: 'nexo-360-9ed4c',
    authDomain: 'nexo-360-9ed4c.firebaseapp.com',
    storageBucket: 'nexo-360-9ed4c.firebasestorage.app',
    measurementId: 'G-13T52PYKJE',
  );
}
